[workspace]
members = [
    "cyphal",
    "cyphal-bxcan",
    "cyphal-can", "cyphal-fdcan",
    "cyphal-serial",
    "cyphal-socketcan",
    "cyphal-udp", "cyphal-udpsocket",
    "dsdl",
]
resolver = "2"
