[toolchain]
channel = "1.78"
components = ["rust-src", "rustfmt", "llvm-tools"]
targets = [
    "thumbv7em-none-eabi",
    "thumbv7m-none-eabi",
    "thumbv6m-none-eabi",
    "thumbv7em-none-eabihf",
    "thumbv8m.main-none-eabihf",
    "armv7-unknown-linux-gnueabihf",
    "aarch64-unknown-linux-gnu",
    "x86_64-unknown-linux-gnu",
]
