[package]
name = "cyphal-embassy"
description = "Open Cyphal CAN Transport Implementation for embassy]"
edition.workspace = true
readme.workspace = true
repository.workspace = true
license.workspace = true
version = "0.0.0"

[dependencies]
