[package]
name = "cyphal-bxcan"
description = "Open Cyphal BXCAN Rust Implementation"
readme = "README.md"
repository = "https://github.com/cyphal-rs/cyphal"
license = "MIT OR Apache-2.0"
edition = "2021"
version = "0.0.6"

[dependencies]
cyphal = { version = "0.0.6", path = "../cyphal" }
cyphal-can = { version = "0.0.6", path = "../cyphal-can" }
bxcan = "0.7.0"
