[package]
name = "cyphal-fdcan"
description = "Open Cyphal FDCAN Rust Implementation"
readme = "README.md"
repository = "https://github.com/cyphal-rs/cyphal"
license = "MIT OR Apache-2.0"
edition = "2021"
version = "0.0.0"

[dependencies]
