[package]
name = "cyphal-udp"
description = "Open Cyphal UDP Transport Rust Implementation"
readme = "README.md"
repository = "https://github.com/cyphal-rs/cyphal"
license = "MIT OR Apache-2.0"
edition = "2021"
version = "0.0.7"

[dependencies]
cyphal = { version = "0.0.7", path = "../cyphal" }
