[package]
name = "cyphal-udp"
description = "Open Cyphal UDP Transport Implementation"
edition.workspace = true
readme.workspace = true
repository.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
cyphal = { version = "0.0.9", path = "../cyphal" }
