[package]
name = "cyphal"
description = "Open Cyphal Rust Implementation"
categories = ["embedded", "hardware-support", "no-std"]
keywords = ["CAN", "Drone", "UAV", "UAVCAN", "OpenCyphal"]
edition = "2021"
readme = "README.md"
repository = "https://github.com/sigmasystems/cyphal"
license = "MIT OR Apache-2.0"
version = "0.0.2"

[features]
can = ["dep:embedded-can"]
crc = []
socketcan = ["can", "dep:socketcan"]

[dependencies]
embedded-can = { version = "0.4.1", optional = true, default-features = false }
socketcan = { version = "3.3.0", optional = true }
