[package]
name = "cyphal-socketcan"
description = "Open Cyphal SocketCAN Rust Implementation"
readme = "README.md"
repository = "https://github.com/cyphal-rs/cyphal"
license = "MIT OR Apache-2.0"
edition = "2021"
version = "0.0.5"

[dependencies]
cyphal-can = { version = "0.0.5", path = "../cyphal-can" }
