[package]
name = "dsdl"
description = "Open Cyphal DSDL Rust Implementation"
categories = ["embedded", "hardware-support"]
keywords = ["CAN", "Drone", "UAV", "UAVCAN", "OpenCyphal"]
edition = "2021"
readme = "README.md"
repository = "https://github.com/sigmasystems/cyphal"
license = "MIT OR Apache-2.0"
version = "0.0.2"

[dependencies]
cyphal = { version = "0.0.2", path = "../cyphal" }
