name: CI
on: [push, pull_request]

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: 1.75.0
        components: clippy, rustfmt

    - name: Check with no features
      run: cargo check

    - name: Check with can feature
      run: cargo check --features "can"

    - name: Check with socketcan feature with CAN 2.0
      run: cargo check --features "can,socketcan"

    - name: Check with socketcan feature with CAN FD
      run: cargo check --features "canfd,socketcan"

    - name: Run CAN 2.0 tests
      run: cargo test --features "can"

    - name: Run CAN FD tests
      run: cargo test --features "canfd"

    - name: Analyze your code
      run: cargo clippy -- --deny=warnings

    - name: Verify formatting
      run: cargo fmt --all --check

    - name: Publish cyphal package
      if: startsWith(github.event.ref, 'refs/tags/v')
      run: cargo publish --package cyphal --token ${{ secrets.CARGO_REGISTRY_TOKEN }}

    - name: Publish dsdl package
      if: startsWith(github.event.ref, 'refs/tags/v')
      run: cargo publish --package dsdl --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
