name: CI
on: [push, pull_request]

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        components: clippy, rustfmt

    - name: Check
      run: cargo check

    - name: Run tests
      run: cargo test

    - name: Analyze your code
      run: cargo clippy -- --deny=warnings

    - name: Verify formatting
      run: cargo fmt --all --check

    - name: Publish cyphal package
      if: startsWith(github.event.ref, 'refs/tags/v')
      run: cargo publish --package cyphal --token ${{ secrets.CARGO_REGISTRY_TOKEN }}

    - name: Publish cyphal-can package
      if: startsWith(github.event.ref, 'refs/tags/v')
      run: cargo publish --package cyphal-can --token ${{ secrets.CARGO_REGISTRY_TOKEN }}

    - name: Publish cyphal-socketcan package
      if: startsWith(github.event.ref, 'refs/tags/v')
      run: cargo publish --package cyphal-socketcan --token ${{ secrets.CARGO_REGISTRY_TOKEN }}

    - name: Publish dsdl package
      if: startsWith(github.event.ref, 'refs/tags/v')
      run: cargo publish --package dsdl --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
