name: CI
on: [push, pull_request]

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        components: clippy, rustfmt

    - name: Verify formatting
      run: cargo fmt --all --check

    - name: Code analysis
      run: cargo clippy -- --deny=warnings

  embedded:
    name: Embedded
    runs-on: ubuntu-latest
    needs: analyze

    strategy:
      fail-fast: false
      matrix:
        include:
          - TARGET: thumbv7em-none-eabi

          - TARGET: thumbv7m-none-eabi

          - TARGET: thumbv6m-none-eabi

          - TARGET: thumbv7em-none-eabihf

          - TARGET: thumbv8m.main-none-eabihf

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        target: ${{ matrix.TARGET }}

    - name: Check
      run: cargo check --workspace --target ${{ matrix.TARGET }} --exclude cyphal-socketcan --exclude cyphal-udpsocket --exclude dsdl

  linux:
    name: Linux
    runs-on: ubuntu-latest
    needs: analyze

    strategy:
      fail-fast: false
      matrix:
        include:
          - TARGET: armv7-unknown-linux-gnueabihf

          - TARGET: aarch64-unknown-linux-gnu

          - TARGET: x86_64-unknown-linux-gnu
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        target: ${{ matrix.TARGET }}

    - name: Check
      run: cargo check

    - name: Run tests
      run: cargo test

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: [embedded, linux]
    if: startsWith(github.event.ref, 'refs/tags/v')

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable

    - name: Publish cyphal package
      run: cargo publish --package cyphal --token ${{ secrets.CARGO_REGISTRY_TOKEN }}

    - name: Publish cyphal-can package
      run: cargo publish --package cyphal-can --token ${{ secrets.CARGO_REGISTRY_TOKEN }}

    - name: Publish cyphal-bxcan package
      run: cargo publish --package cyphal-bxcan --token ${{ secrets.CARGO_REGISTRY_TOKEN }}

    - name: Publish cyphal-fdcan package
      run: cargo publish --package cyphal-fdcan --token ${{ secrets.CARGO_REGISTRY_TOKEN }}

    - name: Publish cyphal-socketcan package
      run: cargo publish --package cyphal-socketcan --token ${{ secrets.CARGO_REGISTRY_TOKEN }}

    - name: Publish dsdl package
      run: cargo publish --package dsdl --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
