name: DSDL CI
on: [push, pull_request]

jobs:
  ci:
    name: Pipeline
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: dtolnay/rust-toolchain@1.75
      with:
        components: clippy, rustfmt

    - name: Check with no features
      run: cargo check --package dsdl

    - name: Run tests
      run: cargo test --package dsdl --all-features
  
    - name: Analyze your code
      run: cargo clippy --package dsdl -- --deny=warnings

    - name: Verify formatting
      run: cargo fmt --package dsdl --check
